FIX: Make width attribute default to null in ResizableImage
Error: 'No value supplied for attribute width'
Fixed by setting width default to null instead of this.options.defaultWidth

This allows images to be inserted without explicit width/height values